### PR TITLE
[6.x] Fix Tenant ID on Webhook event

### LINKED ISSUE #89: [BUG] When using multiple tenants, the tenantId from the web hooks should be used
When using multiple tenants, the tenantId from the web hooks should be used

See screenshot for the fix.

image

```
    public function getResource()
    {
        if ($this->getEventCategory() === 'INVOICE') {
            return $this->accountingApi
                ->getInvoice($this->getTenantId(), $this->getResourceId())
                ->getInvoices()[0];
        }
        if ($this->getEventCategory() === 'CONTACT') {
            return $this->accountingApi
                ->getContact($this->getTenantId(), $this->getResourceId())
                ->getContacts()[0];
        }
    }
```

### PR DESCRIPTION
**Pull request by JamesFreeman**
Closes #89

### CODE REVIEW

File: tests/Unit/WebhookEventTest.php [hunk 1]
```diff
@@ -47,7 +47,7 @@ public function test_you_can_get_a_webhook_for_invoice()
         $this->assertEquals('2021-01-01T00:00:00.000Z', $sut->getEventDateUtc());
         $this->assertEquals('CREATE', $sut->getEventType());
         $this->assertEquals('INVOICE', $sut->getEventCategory());
-        $this->assertEquals('456', $sut->getTenantId());
+        $this->assertEquals('webhook-tentant-id', $sut->getTenantId());
```
Comment (hailwood) [inline tests/Unit/WebhookEventTest.php:50]: I know it doesn't matter since it's just a test string, but can we please fix these to `tenant` instead of `tentant` :)

Comment (JamesFreeman) [reply tests/Unit/WebhookEventTest.php]: Good catch :)

**Comment by hailwood** [comment]
Looking good @JamesFreeman,
I just did one small change to remove the redundant `->andReturn` off the never calls :)

Thanks!
